import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, copyFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const exec = promisify(execFile);
test('setup in a disposable directory generates independent secrets and preserves the database URL', { skip: process.platform !== 'win32' }, async t => {
  const prefix = join(tmpdir(), 'bairui-env-check-');
  const folder = await mkdtemp(prefix);
  t.after(async () => { assert.ok(resolve(folder).startsWith(resolve(prefix))); await rm(folder, { recursive: true, force: true }); });
  await mkdir(join(folder, 'scripts'));
  await copyFile(new URL('./setup-env.ps1', import.meta.url), join(folder, 'scripts/setup-env.ps1'));
  await copyFile(new URL('../.env.example', import.meta.url), join(folder, '.env.example'));
  const url = 'postgresql://app:local%24test@127.0.0.1:5432/test_only';
  const args = ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', join(folder, 'scripts/setup-env.ps1'), '-DatabaseUrl', url];
  await exec('powershell', args, { windowsHide: true });
  const text = await readFile(join(folder, '.env'), 'utf8');
  const entries = Object.fromEntries(text.split(/\r?\n/).filter(line => /^[A-Z_]+=/.test(line)).map(line => [line.slice(0, line.indexOf('=')), line.slice(line.indexOf('=') + 1)]));
  assert.equal(entries.BAIRUI_PLATFORM_MODE, 'platform');
  assert.equal(entries.BAIRUI_AUTH_MODE, 'better-auth');
  assert.equal(entries.DATABASE_URL, url);
  assert.match(entries.BETTER_AUTH_SECRET, /^[a-f0-9]{96}$/);
  assert.match(entries.BAIRUI_SESSION_SECRET, /^[a-f0-9]{96}$/);
  assert.notEqual(entries.BETTER_AUTH_SECRET, entries.BAIRUI_SESSION_SECRET);
  await exec('powershell', args, { windowsHide: true });
  assert.equal(await readFile(join(folder, '.env'), 'utf8'), text);
});
